controll advice를 사용해서 처리해보자

(AuthController.java)

```
@PostMapping("/auth/signup")
public String signup(@Valid SignupDto signupDto, BindingResult bindingResult) {

		if(bindingResult.hasErrors()) {

			Map<String,String> errorMap = new HashMap<>();

			for(FieldError error : bindingResult.getFieldErrors()) {
				errorMap.put(error.getField(), error.getDefaultMessage());
				System.out.println("here"+error.getDefaultMessage());
			}
			//return "오류남";
            throw new RuntimeException("유혀성검사 실패함");
		}else {
			User user = signupDto.toEntity();
			User userEntity = authService.회원가입(user);
			System.out.println("확인용"+userEntity);
			return "auth/signin";
		}
	}
```

일단 @Responsebody를 지워주었고 return "오류남" 데이터(String)로 리턴되던 이부분을 throw new RuntimeException("유효성검사실패함") 예외처리가 강제발생하게 처리해주었다.

![Visual Studio Code](/img/runtimeException.png)

---

(ControllerExceptionHandler.java)

```
@RestController
@ControllerAdvice
public class ControllerExceptionHandler {

	@ExceptionHandler(RuntimeException.class) // RuntimeException을 발생하는 모든 exception을 이 함수가 가로챔
	public String validationException(RuntimeException e) {
		return e.getMessage();
	}

}

```

@ControllAdvice 어노테이션을 붙이면 모든 exception을 다 낚아챔

낚아채고 나면 응답을 해야하는데, 이를 위해서 @RestController를 붙여서 데이터를 리턴해주도록 하겠다.

@ExceptionHandler(RuntimeException.class)

---

![Visual Studio Code](/img/controllAdvice.png)

=> @controllerAdvice를 통해 낚아챈 후 @RestController를 통해 데이터(String)을 리턴하도록 하였으므로 훨씬 더 깔끔하게 응답된 것을 볼 수 있다.

---

but, 문제는

![Visual Studio Code](/img/runtimeException2.png)

=>우리는 해당 error.getDefaultMessage()를 리턴해서 에러의 내용을 확인하고싶은데

![Visual Studio Code](/img/runtimeException3.png)

=> RuntimeException클래스를 살펴보면 매개변수로 String만 받도록 되어있다.

=>handler 패키지에 ex패키지를 만들고 그안에 CustomValidationException.java 클래스를 만들어주겠다.

(CustomValidationException.java)

```
public class CustomValidationException extends RuntimeException{

	//시리얼번호는 객체를 구분할 때 쓰는것 = 중요한거 아님
	private static final long serialVersionUID = -807520916259076805L;

	/*field*/
	//private String message;
	private Map<String,String>errorMap;

	/*constructor*/
	public CustomValidationException(String message,Map<String,String>errorMap) {
		super(message);
		//this.message = message;
		this.errorMap = errorMap;
	}

	/*getter*/
	public Map<String,String>getErrorMap(){
		return errorMap;
	}

}
```

필드값 message를 리턴하는 getter를 만들지 않은 이유는 String 값은 리턴하지 않을 것이기 때문이다.

근데 생성자에 매개변수로 넣은이유는 결국 하이라키구조상 상위부모에게 String값을 던져줘야해서이다.

필드로도 굳이 만들필요도 없어서 주석처리

=>즉, CustomValidationException.java 클래스는 RuntimeException을 상속하면서 데이터타입Map인 errorMap을 리턴하기 위해 오버라이딩한 exception클래스인 셈이다.

---

그럼 이제 다시 ControllerExceptionHandler.java로 돌아가서

(ControllerExceptionHandler.java)

```
@RestController
@ControllerAdvice
public class ControllerExceptionHandler {

	@ExceptionHandler(CustomValidationException.class)
	public Map<String,String> validationException(CustomValidationException e) {
		//return e.getMessage();
        return e.getErrorMap();
	}

}
```

RuntimeException.class=>CustomValidationException.class

로 교체 해주고

리턴데이터타입도 Map<String,String> 으로 바꿔주고
e.getErrorMap();을 리턴해주도록 한다.

그리고

(AuthConroller.java)

```
throw new CustomValidationException("유효성검사실패함",errorMap);
```

exception 발생시킬때도 매개변수에 errorMap을 추가해서 넣어준다.

이제 다시 회원가입을 진행해보면

![Visual Studio Code](/img/customException.png)

Map<String,String> 이 리턴이 되었다.
